# Site settings
title: Robin Scheibler
email: robin.scheibler@epfl.ch
description: > # this means to ignore newlines until "baseurl:"
  My name is Robin Scheibler and this is my site. You can find stuff about
  the research and projects I do.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fakufakurevenge
github_username:  fakufaku
linkedin_username: robinscheibler

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

plugins: [jekyll-paginate]

socials:
  - icon: envelope
    url: mailto:robin[dot]scheibler[at]gmail[dot]com
  - icon: github
    url: http://github.com/fakufaku
  - icon: twitter
    url: http://www.twitter.com/fakufakurevenge
  - icon: linkedin
    url: http://www.linkedin.com/in/robinscheibler

# I want to have a collection of projects
collections:
  projects:
    output: true
  pages:
    output: true
